source 'https://rubygems.org'

gem 'rails'

gem 'slim'
gem 'thin'
gem 'mongoid'


gem 'rspec-rails', :group => [:test, :development]
gem 'factory_girl_rails', :group => [:test, :development]

group :development do
end


group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'execjs'
  gem 'therubyracer'

  gem 'uglifier'
end
