source 'https://rubygems.org'

gem 'figaro'

gem 'rails'

gem 'slim', :require => 'slim/logic_less'
gem 'thin'
gem 'mongoid'
gem 'coffee-views'
gem 'draper'
gem 'money-rails'

gem 'carrierwave'
gem 'cloudinary'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-vkontakte'
gem 'omniauth-facebook'
gem 'omniauth-odnoklassniki'
gem 'omniauth-google-oauth2'

group :test, :development do
  gem 'launchy'
  gem 'poltergeist'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'file-monitor'
  
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'

  gem 'spinach-rails'
end

group :assets do
  gem 'bootstrap-sass'
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'execjs'
  gem 'therubyracer'

  gem 'uglifier'
end
