source 'https://rubygems.org'

gem 'rails'

gem 'slim', :require => 'slim/logic_less'
gem 'thin'
gem 'mongoid'
gem 'coffee-views'
gem 'draper'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-vkontakte'
gem 'omniauth-facebook'
gem 'omniauth-odnoklassniki'


gem 'rspec-rails', :group => [:test, :development]
gem 'factory_girl_rails', :group => [:test, :development]

group :development do
end


group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'execjs'
  gem 'therubyracer'

  gem 'uglifier'
end
