guard 'spinach', command_prefix: 'zeus', bundler: false do
  watch(%r|^features/(.*)\.feature|)
  watch(%r|^features/steps/(.*)([^/]+)\.rb|) do |m|
    "features/#{m[1]}#{m[2]}.feature"
  end
end

guard 'rspec', cli: '--color', zeus: true, all_on_start: false, all_after_pass: false do
  watch(%r{^spec/.+_spec\.rb$})
end

